/**
 * Official Organization Constants
 * Maa-Babuji Jankalyan Samiti Chhattisgarh (मां-बाबूजी जनकल्याण समिति छत्तीसगढ़)
 */

export const NGO_DETAILS = {
  nameHi: 'मां-बाबूजी जनकल्याण समिति छत्तीसगढ़',
  nameEn: 'Maa-Babuji Jankalyan Samiti Chhattisgarh',
  shortName: 'MBKS Chhattisgarh',
  regNo: 'जावक क्रमांक 347, दिनांक 26/05/2025',
  address: {
    village: 'भैसमुड़ी (Bhaisamudi)',
    post: 'सिउंड (Siund)',
    ward: 'भाठा पारा, वार्ड नंबर 22, मकान नंबर 651',
    landlord: 'सुखनंदन दास पिता श्री देवीदास',
    tehsil: 'नवागढ़ (Nawagarh)',
    block: 'नवागढ़ (Nawagarh)',
    district: 'जांजगीर-चांपा (Janjgir-Champa)',
    state: 'छत्तीसगढ़ (Chhattisgarh)',
    pincode: '495668',
  },
  contact: {
    phone: '+91 70243 32668',
    whatsapp: '+91 70243 32668',
    email: 'maababujijankalyansamiti@gmail.com',
    helpline: '+91 70243 32668',
  },
  social: {
    facebook: 'https://facebook.com',
    youtube: 'https://youtube.com',
    whatsapp: 'https://wa.me/917024332668',
  },
};

export const BANK_DETAILS = {
  accountName: 'MAA BABUJI JANKALYAN SAMITI CHHATTISGARH SOCIETY',
  accountNameHi: 'मां बाबूजी जनकल्याण समिति छत्तीसगढ़ सोसाइटी',
  bankName: 'Union Bank of India',
  bankNameHi: 'यूनियन बैंक ऑफ इंडिया',
  accountNo: '291121010000113',
  ifsc: 'UBIN0929115',
  branch: 'Janjgir (DD Plaza, Kacheri Chowk, Janjgir, C.G.)',
  branchHi: 'जांजगीर (डीडी प्लाजा, कचहरी चौक, जांजगीर, छ.ग.)',
  accountType: 'Current Account / संस्था का आधिकारिक खाता',
  upiId: 'QR919516133518-2660@unionbankofindia',
  qrCodeImg: '/upi-qr.jpg',
};

export const NGO_OBJECTIVES = [
  {
    id: 1,
    titleHi: 'शासकीय योजनाओं का प्रचार-प्रसार',
    titleEn: 'Government Schemes Awareness',
    descHi: 'केन्द्र एवं राज्य शासन के समस्त जनकल्याणकारी योजनाओं का जन-जन तक प्रचार-प्रसार करना।',
    descEn: 'Disseminating and spreading awareness regarding all Central and State government welfare schemes to the grassroots.',
    iconName: 'Megaphone',
    colorCategory: 'green',
  },
  {
    id: 2,
    titleHi: 'राष्ट्रीय कल्याण एवं स्वास्थ्य सेवा',
    titleEn: 'National Welfare & Healthcare',
    descHi: 'परिवार कल्याण, टीकाकरण, निरक्षरता उन्मूलन, महिला समानता एवं समाज सेवा में सहयोग।',
    descEn: 'Supporting national welfare programs including family care, immunization drives, literacy, and gender equality.',
    iconName: 'HeartPulse',
    colorCategory: 'blue',
  },
  {
    id: 3,
    titleHi: 'सामाजिक कुरीतियों का उन्मूलन',
    titleEn: 'Eradication of Social Evils',
    descHi: 'दहेज प्रथा, लिंग असमानता, नशा मुक्ति, बाल विवाह, बाल श्रम एवं जातिगत भेदभाव का उन्मूलन।',
    descEn: 'Eradicating social evils like dowry, gender discrimination, substance addiction, child marriage, child labor, and caste bias.',
    iconName: 'ShieldAlert',
    colorCategory: 'red',
  },
  {
    id: 4,
    titleHi: 'राष्ट्रीय एकता एवं सामाजिक सद्भावना',
    titleEn: 'National Unity & Social Harmony',
    descHi: 'राष्ट्रीय एकता, सद्भावना, शांति एवं सामाजिक भाईचारे के क्षेत्र में निरंतर कार्य करना।',
    descEn: 'Promoting national integration, peaceful coexistence, communal harmony, and social unity across regions.',
    iconName: 'Users',
    colorCategory: 'gold',
  },
  {
    id: 5,
    titleHi: 'पर्यावरण संरक्षण एवं संवर्धन',
    titleEn: 'Environmental Protection & Conservation',
    descHi: 'वृक्षारोपण, पर्यावरण सुरक्षा, स्वच्छता अभियान एवं हरित छत्तीसगढ़ हेतु कार्य।',
    descEn: 'Fostering environmental protection, afforestation, cleanliness drives, and ecological balance.',
    iconName: 'Leaf',
    colorCategory: 'green',
  },
  {
    id: 6,
    titleHi: 'वृद्धजन एवं दिव्यांग पुनर्वास',
    titleEn: 'Elderly & Divyangjan Care',
    descHi: 'वरिष्ठ नागरिकों (वृद्धजनों) एवं दिव्यांग जनों के पुनर्वास, सहायक उपकरण एवं देखभाल हेतु कार्य।',
    descEn: 'Providing rehabilitation, assistive devices, and dignity care for senior citizens and persons with disabilities.',
    iconName: 'Accessibility',
    colorCategory: 'pink',
  },
  {
    id: 7,
    titleHi: 'युवा व्यक्तित्व विकास एवं संस्कृति',
    titleEn: 'Youth Personality & Cultural Development',
    descHi: 'खेलकूद प्रतियोगिताएं, सांस्कृतिक कार्यक्रम एवं युवाओं के सर्वांगीण विकास गतिविधियां।',
    descEn: 'Organizing sports tournaments, cultural heritage events, and youth leadership activities.',
    iconName: 'Trophy',
    colorCategory: 'gold',
  },
  {
    id: 8,
    titleHi: 'युवा शिक्षा एवं व्यावसायिक प्रशिक्षण',
    titleEn: 'Education & Vocational Training',
    descHi: 'युवाओं के लिए उच्च शिक्षा सहायता, कंप्यूटर शिक्षा एवं स्वरोजगार हेतु व्यावसायिक प्रशिक्षण।',
    descEn: 'Providing educational guidance, digital literacy, and skill-based vocational training for youth self-employment.',
    iconName: 'GraduationCap',
    colorCategory: 'green',
  },
  {
    id: 9,
    titleHi: 'रक्तदान प्रोत्साहन एवं जागरूकता',
    titleEn: 'Blood Donation Awareness Drives',
    descHi: 'युवाओं को स्वेच्छा से रक्तदान हेतु प्रोत्साहित करना एवं आपातकालीन रक्त सेवा सहायता उपलब्ध कराना।',
    descEn: 'Encouraging youth for voluntary blood donation and managing emergency blood assistance networks.',
    iconName: 'Droplet',
    colorCategory: 'red',
  },
  {
    id: 10,
    titleHi: 'जल संरक्षण एवं संचयन',
    titleEn: 'Water Conservation Initiatives',
    descHi: 'वर्षा जल संचयन, जल स्रोतों का जीर्णोद्धार एवं जल बचत जागरूकता अभियान चलाना।',
    descEn: 'Conducting rainwater harvesting projects, pond restoration, and water preservation campaigns.',
    iconName: 'Droplets',
    colorCategory: 'blue',
  },
];

export const NAVIGATION_LINKS = [
  { path: '/', labelHi: 'मुख्य पृष्ठ', labelEn: 'Home' },
  { path: '/about', labelHi: 'हमारे बारे में', labelEn: 'About Us' },
  { path: '/objectives', labelHi: 'उद्देश्य', labelEn: 'Objectives' },
  { path: '/programs', labelHi: 'कार्यक्रम', labelEn: 'Programs' },
  { path: '/projects', labelHi: 'परियोजनाएं', labelEn: 'Projects' },
  { path: '/impact', labelHi: 'सामाजिक प्रभाव', labelEn: 'Impact' },
  { path: '/events', labelHi: 'गतिविधियां', labelEn: 'Events' },
  { path: '/gallery', labelHi: 'गैलरी', labelEn: 'Gallery' },
  { path: '/news', labelHi: 'समाचार', labelEn: 'News & Blog' },
  { path: '/reports', labelHi: 'रिपोर्ट्स', labelEn: 'Reports' },
  { path: '/contact', labelHi: 'संपर्क करें', labelEn: 'Contact' },
];
